#
# Spec file generated by kdist version v0.0.4-57-g3d97
#
Name:          kernel-source
Summary:       Linux kernel source files
Version:       3.1.5
Release:       %mkrel 1.1
License:       GPL v2
Group:         System/Kernel and hardware
URL:           http://www.kernel.org
Source:        kernel-source-3.1.5-1.tar.bz2
Buildarch:     noarch
BuildRoot:     %{_tmppath}/%{name}-%{version}-root
AutoReqProv:   no
BuildRequires: rsync

%define debug_package %{nil}
%define __check_files %{nil}

%description
This package provides the whole kernel source files.

%prep
%setup -q -n kernel-source-3.1.5-1

%install
mkdir -p   %{buildroot}/usr/src/linux-3.1.5-1
rsync -a . %{buildroot}/usr/src/linux-3.1.5-1

%clean
rm -rf %{buildroot}

%files
%defattr (-, root, root)
/usr/src

%changelog
* Tue Dec 13 2011 Franck Bui <franck.bui@mandriva.com> 3.1.5-1
  + Mandriva Release v3.1.5-1
  + pci: Rework ASPM disable code
  + usb: ehci: make HC see up-to-date qh/qtd descriptor ASAP
  + btrfs: btrfs_calc_avail_data_space cope with no read/write devices V2
  + gpu drm mach64 2.6.39 buildfix
  + vfs: introduce clone_private_mount()
  + vfs: export do_splice_direct() to modules
  + vfs: add i_op->open()
  + Mandriva Linux boot logo.
  + media video pwc no ads in dmesg
  + media video pwc lie in proc usb devices
  + usb storage unusual_devs add id 2.6.37 buildfix
  + Change to usb storage of unusual_dev.
  + Add blacklist of usb hid modules
  + bluetooth hci_usb disable isoc transfers
  + sound alsa hda ad1884a hp dc model
  + Support a Bluetooth SCO.
  + include kbuild export pci_ids
  + platform x86 add shuttle wmi driver
  + net netfilter psd 2.6.35 buildfix
  + ipt_psd: Mandriva changes
  + net netfilter psd
  + net netfilter IFWLOG 2.6.37 buildfix
  + net netfilter IFWLOG 2.6.35 buildfix
  + net netfilter IFWLOG mdv
  + net netfilter IFWLOG
  + net sis190 fix list usage
  + kbuild compress kernel modules on installation
  + gpu drm mach64 2.6.37 buildfix
  + gpu drm mach64 2.6.36 buildfix
  + gpu drm mach64 fix for changed drm_ioctl
  + gpu drm mach64 fix for changed drm_pci_alloc
  + Adapt mach64 to build with 2.6.31 series kernels
  + gpu drm mach64 fixes
  + gpu drm mach64
  + agp/intel: add new host bridge id for Q57 system
  + mpt scsi modules for VMWare's emulated
  + ide pci sis5513 965
  + ppscsi: build fix for 2.6.39
  + scsi megaraid new sysfs name
  + scsi ppscsi mdvbz45393
  + scsi ppscsi update for scsi_data_buffer
  + scsi ppscsi sg helper update
  + scsi ppscsi_fixes
  + scsi ppscsi-2.6.2
  + acpi video add blacklist to use vendor driver
  + acpi processor M720SR limit to C2
  + CLEVO M360S acpi irq workaround
  + acpi add proc event regs
  + acpi dsdt initrd v0.9c fixes
  + acpi dsdt initrd v0.9c 2.6.28
  + UBUNTU: SAUCE: isapnp_init: make isa PNP scans occur async
  + pnp pnpbios off by default
  + pci add ALI M5229 ide compatibility mode quirk
  + Card bus's PCI last bus
  + x86, cpufreq: set reasonable default for scaling_min_freq with p4-clockmod
  + x86 cpufreq speedstep dothan 3
  + default to "power_off" when SMP kernel is used on single processo
  + x86 boot video 80x25 if break
  + x86 pci toshiba equium a60 assign busses
  + kdist: make the config name part of the localversion
  + kdist: give a name to the config file
